services:
  tor1:
    build:
      context: ../apps/proxy
      dockerfile: Dockerfile.dev
    container_name: tor_proxy_1
    ports:
      - "9051:9050"
    tty: true
    stdin_open: true

  tor2:
    build:
      context: ../apps/proxy
      dockerfile: Dockerfile.dev
    container_name: tor_proxy_2
    ports:
      - "9052:9050"
    tty: true
    stdin_open: true

  tor3:
    build:
      context: ../apps/proxy
      dockerfile: Dockerfile.dev
    container_name: tor_proxy_3
    ports:
      - "9053:9050"
    tty: true
    stdin_open: true

  crawler:
    build:
      context: ../apps/crawler
      dockerfile: Dockerfile.dev
    container_name: crawler_service
    volumes:
      - ../apps/crawler:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # scraper:
  #   build:
  #     context: ../apps/scraper
  #     dockerfile: Dockerfile.dev
  #   container_name: scraper_service
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ../apps/scraper:/app
  #   working_dir: /app
  #   command: tail -f /dev/null
  #   depends_on:
  #     - redis
  redis:
    image: redis:8.0-rc1-alpine
    container_name: redis_service
    volumes:
      - ./db/redis:/data
    ports:
      - "6379:6379"

#  mongodb:
#    image: mongo:8.0.9
#    container_name: mongodb_service
#    ports:
#      - "27017:27017"
#    env_file:
#      - ../apps/crawler/.env
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME
#      - MONGO_INITDB_ROOT_PASSWORD
#    volumes:
#      - ./db/mongodb:/data
#      - ./logs/mongodb:/var/log/mongodb

  neo4j:
    image: neo4j:5.26.5-community-bullseye
    container_name: neo4j_service
    ports:
      - "7474:7474"
    volumes:
      - ./db/neo4j:/data
      - ./logs/neo4j:/var/log/neo4j

volumes:
  mongodb_data:
  redis_data:
  neo4j_data:
