services:
  tor1:
    build:
      context: ../apps/proxy
      dockerfile: Dockerfile.dev
    container_name: tor_proxy_1
    ports:
      - "9051:9050"
    tty: true
    stdin_open: true

  tor2:
    build:
      context: ../apps/proxy
      dockerfile: Dockerfile.dev
    container_name: tor_proxy_2
    ports:
      - "9052:9050"
    tty: true
    stdin_open: true

  tor3:
    build:
      context: ../apps/proxy
      dockerfile: Dockerfile.dev
    container_name: tor_proxy_3
    ports:
      - "9053:9050"
    tty: true
    stdin_open: true

  crawler:
    build:
      context: ../apps/crawler
      dockerfile: Dockerfile.dev
    container_name: crawler_service
    volumes:
      - ../apps/crawler:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # scraper:
  #   build:
  #     context: ../apps/scraper
  #     dockerfile: Dockerfile.dev
  #   container_name: scraper_service
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ../apps/scraper:/app
  #   working_dir: /app
  #   command: tail -f /dev/null
  #   depends_on:
  #     - redis
  redis:
    image: redis:latest
    container_name: redis_service
    volumes:
      - ./db/redis:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data:
