FROM golang:1.24

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    iputils-ping \
    curl \
    vim \
    net-tools && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# On copie d'abord uniquement les fichiers de dépendances
COPY go.mod ./

# On supprime go.sum s'il existe pour le reconstruire proprement
RUN rm -f go.sum

# On met à jour go.mod et on génère go.sum
RUN go mod tidy

# On copie le reste du code source
COPY . .

CMD ["go", "run", "cmd/main.go"]
