# Dockerfile
FROM golang:1.24 as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o scraper ./cmd/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
RUN adduser -D -g '' scraperuser
USER scraperuser
WORKDIR /home/scraperuser
COPY --from=builder /app/scraper .
ENTRYPOINT [ "./scraper" ]
