apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: crawler
              image: votre-nom/crawler:latest
              env:
                - name: MONGO_URI
                  value: "mongodb://mongodb-service:27017/web_crawler_db"
                - name: ELASTICSEARCH_HOST
                  value: "http://elasticsearch-service:9200"
                - name: REDIS_HOST
                  value: "redis-service:6379"
          restartPolicy: OnFailure
