name: Global Security/Secrets

on:
  push:
    branches:
      - main
      - develops
  pull_request:
    branches:
      - main

jobs:
  secrets-global:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find secrets (global)
        uses: gitleaks/gitleaks-action@v2

  docker-scan-global:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan Docker images (full)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
